package com.frequentis.semnotam.schema._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-23T10:04:30.259+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://ws.semnotam.frequentis.com/", name = "ContainerDescriptionService")
@XmlSeeAlso({ObjectFactory.class})
public interface ContainerDescriptionService {

    @WebMethod
    @RequestWrapper(localName = "getInterestFromConcept", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetInterestFromConcept")
    @ResponseWrapper(localName = "getInterestFromConceptResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetInterestFromConceptResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getInterestFromConcept(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "selectConceptForFacet", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.SelectConceptForFacet")
    @ResponseWrapper(localName = "selectConceptForFacetResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.SelectConceptForFacetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<String> selectConceptForFacet(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getConceptForInterest", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetConceptForInterest")
    @ResponseWrapper(localName = "getConceptForInterestResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetConceptForInterestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getConceptForInterest(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
