
package com.frequentis.semnotam.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.10
 * Mon Oct 30 13:05:31 CET 2017
 * Generated source version: 3.1.10
 */

@XmlRootElement(name = "getNotamConcepts", namespace = "http://ws.semnotam.frequentis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getNotamConcepts", namespace = "http://ws.semnotam.frequentis.com/")

public class GetNotamConcepts {


}

