package com.frequentis.semnotam.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-23T10:04:48.305+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://ws.semnotam.frequentis.com/", name = "SemNotamWebService")
@XmlSeeAlso({aero.aixm.ObjectFactory.class, org.isotc211.gss.ObjectFactory.class, aero.aixm.message.ObjectFactory.class, org.isotc211.gsr.ObjectFactory.class, org.isotc211.gts.ObjectFactory.class, org.w3.xlink.v1999.ObjectFactory.class, ObjectFactory.class, aero.aixm.event.ObjectFactory.class, net.opengis.ows._1.ObjectFactory.class, org.isotc211.gco.ObjectFactory.class, com.frequentis.semnotam.schema._1.ObjectFactory.class, net.opengis.fes._2.ObjectFactory.class, net.opengis.wfs._2.ObjectFactory.class, net.opengis.gml.ObjectFactory.class, org.isotc211.gmd.ObjectFactory.class})
public interface SemNotamWebService {

    @WebMethod
    @RequestWrapper(localName = "getAerodromeById", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetAerodromeById")
    @ResponseWrapper(localName = "getAerodromeByIdResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetAerodromeByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.frequentis.semnotam.schema._1.AerodromeType getAerodromeById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAtsSegmentById", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetAtsSegmentById")
    @ResponseWrapper(localName = "getAtsSegmentByIdResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetAtsSegmentByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.frequentis.semnotam.schema._1.AtsSegmentType getAtsSegmentById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getFirIds", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetFirIds")
    @ResponseWrapper(localName = "getFirIdsResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetFirIdsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getFirIds();

    @WebMethod
    @RequestWrapper(localName = "evaluate", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.Evaluate")
    @ResponseWrapper(localName = "evaluateResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.frequentis.semnotam.schema._1.InterestSpecResultType evaluate(
        @WebParam(name = "arg0", targetNamespace = "")
        com.frequentis.semnotam.schema._1.InterestSpecificationType arg0
    );

    @WebMethod
    @RequestWrapper(localName = "evaluateInterestSpecificationForFeatureCollection", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateInterestSpecificationForFeatureCollection")
    @ResponseWrapper(localName = "evaluateInterestSpecificationForFeatureCollectionResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateInterestSpecificationForFeatureCollectionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.frequentis.semnotam.schema._1.InterestSpecResultType evaluateInterestSpecificationForFeatureCollection(
        @WebParam(name = "arg0", targetNamespace = "")
        net.opengis.wfs._2.FeatureCollectionType arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.frequentis.semnotam.schema._1.InterestSpecificationType arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2
    );

    @WebMethod
    @RequestWrapper(localName = "evaluateInterestSpecificationForNotamSet", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateInterestSpecificationForNotamSet")
    @ResponseWrapper(localName = "evaluateInterestSpecificationForNotamSetResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateInterestSpecificationForNotamSetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.frequentis.semnotam.schema._1.InterestSpecResultType evaluateInterestSpecificationForNotamSet(
        @WebParam(name = "arg0", targetNamespace = "")
        com.frequentis.semnotam.schema._1.InterestSpecResultType arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.frequentis.semnotam.schema._1.InterestSpecificationType arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getTransitionSegmentById", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetTransitionSegmentById")
    @ResponseWrapper(localName = "getTransitionSegmentByIdResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetTransitionSegmentByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.frequentis.semnotam.schema._1.TransitionSegmentType getTransitionSegmentById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getFirById", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetFirById")
    @ResponseWrapper(localName = "getFirByIdResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetFirByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.frequentis.semnotam.schema._1.FirType getFirById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "evaluateNotamSet", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateNotamSet")
    @ResponseWrapper(localName = "evaluateNotamSetResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateNotamSetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.frequentis.semnotam.schema._1.InterestSpecResultType evaluateNotamSet(
        @WebParam(name = "arg0", targetNamespace = "")
        com.frequentis.semnotam.schema._1.InterestSpecificationType arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.frequentis.semnotam.schema._1.InterestSpecResultType arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getTransitionSegmentIds", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetTransitionSegmentIds")
    @ResponseWrapper(localName = "getTransitionSegmentIdsResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetTransitionSegmentIdsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getTransitionSegmentIds();

    @WebMethod
    @RequestWrapper(localName = "getAircraftTypeIds", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetAircraftTypeIds")
    @ResponseWrapper(localName = "getAircraftTypeIdsResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetAircraftTypeIdsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getAircraftTypeIds();

    @WebMethod
    @RequestWrapper(localName = "getAtsSegmentIds", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetAtsSegmentIds")
    @ResponseWrapper(localName = "getAtsSegmentIdsResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetAtsSegmentIdsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getAtsSegmentIds();

    @WebMethod
    @RequestWrapper(localName = "evaluateFeatureCollection", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateFeatureCollection")
    @ResponseWrapper(localName = "evaluateFeatureCollectionResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateFeatureCollectionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.frequentis.semnotam.schema._1.InterestSpecResultType evaluateFeatureCollection(
        @WebParam(name = "arg0", targetNamespace = "")
        com.frequentis.semnotam.schema._1.InterestSpecificationType arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        net.opengis.wfs._2.FeatureCollectionType arg1
    );

    @WebMethod
    @RequestWrapper(localName = "evaluateInterestSpecification", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateInterestSpecification")
    @ResponseWrapper(localName = "evaluateInterestSpecificationResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.EvaluateInterestSpecificationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.frequentis.semnotam.schema._1.InterestSpecResultType evaluateInterestSpecification(
        @WebParam(name = "arg0", targetNamespace = "")
        com.frequentis.semnotam.schema._1.InterestSpecificationType arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getAerodromeIds", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetAerodromeIds")
    @ResponseWrapper(localName = "getAerodromeIdsResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetAerodromeIdsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getAerodromeIds();

    @WebMethod
    @RequestWrapper(localName = "getNotamConcepts", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetNotamConcepts")
    @ResponseWrapper(localName = "getNotamConceptsResponse", targetNamespace = "http://ws.semnotam.frequentis.com/", className = "com.frequentis.semnotam.ws.GetNotamsConceptsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> getNotamConcepts();
}
