
package com.frequentis.semnotam.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Feb 21 16:18:46 CET 2017
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "sumResponse", namespace = "http://ws.semnotam.frequentis.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sumResponse", namespace = "http://ws.semnotam.frequentis.com/")

public class SumResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

